### ISSUE TITLE
More explanation on box-sizing: border-box;

### ISSUE THREAD

**Issue by moinul-ai** [cssconf/CSSclasses--old#83]
It will be nice to show the difference between "manually specifying the box properties" and using "box-sizing" using similar graphics shown for box-model in the learning material. It was not very clear at the first go. May be it can be shown as below.

Here we Manually specify the box property for div1:

``` css
#div1 {
  width: 500px;
  border: 5px solid black;
  padding: 5px;
  margin: 5px;
}
```

![screen shot 2015-06-07 at 12 35 54](https://cloud.githubusercontent.com/assets/4951199/8023566/12365fb2-0d11-11e5-89b6-d81c0584da0c.png)

Here we use box-sizing: border-box for div2. Here, default value for border is added to the box by the browser;

``` css
#div2 {
  width: 500px;
  color: red;
  border: dotted red;
  box-sizing: border-box;
}
```

![screen shot 2015-06-07 at 12 30 30](https://cloud.githubusercontent.com/assets/4951199/8023567/1c02f74e-0d11-11e5-858f-b3fb401aad8a.png)
